api:
  host: https://vintra.ciskauskas.lt
  path: /otp/routers/default
  basePath: /otp

units: metric

dateTime:
  dateFormat: yyyy-MM-dd
  timeFormat: HH:mm

persistence:
  enabled: true
  strategy: localStorage

translateExternalLinks: false

map:
  initLat: 54.6872
  initLon: 25.2797
  baseLayers:
    - name: Gatvės
      url: //basemaps.cartocdn.com/gl/positron-gl-style/style.json
      attribution: 'Map tiles: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, &copy; <a href="https://carto.com/attributions">CARTO</a>'
      maxZoom: 20

geocoder:
  type: PHOTON
  baseUrl: https://photon.komoot.io
  focusPoint:
    lat: 54.6872
    lon: 25.2797
  boundary:
    rect:
      minLon: 20.9
      maxLon: 26.85
      minLat: 53.85
      maxLat: 56.45
  geocoderResultsOrder: ['STATIONS', 'STOPS', 'OTHER']

modes:
  modeButtons:
    - iconName: bus
      key: transit
      modes:
        - mode: TRANSIT
    - iconName: walk
      key: walk
      modes:
        - mode: WALK
  initialState:
    enabledModeButtons:
      - transit
  modeSettingDefinitions:
    - applicableMode: TRANSIT
      default: false
      key: wheelchair
      iconName: wheelchair
      type: CHECKBOX
  transitModes:
    - mode: ["TROLLEYBUS", "BUS"]
      overrideMode: BUS
      label: Autobusas / Troleibusas
      color: "#e3000f"
    - mode: RAIL
      label: Traukinys
    - mode: FERRY
      label: Keltas

itinerary:
  validModeCombinations: [
    ['WALK'],
    ['WALK', 'TRANSIT'],
    ['WALK', 'TRANSIT', 'PERSONAL'],
    ['WALK', 'TRANSIT', 'SHARED'],
    ['WALK', 'SHARED'],
  ]
  showRouteFares: false
  showPlanFirstLastButtons: false
  showApproximatePrefixAccessLegs: false
  showAlertEffectiveDateTimeText: true
  showAllWalkLegs: false
  strictItineraryFiltering: false
  renderRouteNamesInBlocks: true
  fillModeIcons: true
  allowUserAlertCollapsing: true
  defaultFareType: { mediumId: null, riderCategoryId: null }
  showHeaderText: false
  showBatchUiItineraryHeaders: false
  hideSkeletons: true
  customBatchUiBackground: true
  groupByMode: true
  groupTransitModes: true
  mergeItineraries: true
  showFirstResultByDefault: false
  onlyShowCountdownForRealtime: true
  showScheduleDeviation: true
  showLegDurations: false
  displayTripInPastError: true
  syncSortWithDepartArrive: true

advancedSettingsPanel:
  saveAndReturnButton: true

language:
  lt:
    name: Lietuvių

localization:
  defaultLocale: lt
